### ISSUE TITLE
Guidance needed; Fargate and Multiline logs

### ISSUE THREAD

**Issue by f0o** [aws/aws-for-fluent-bit#220]
Hi,

I'm a bit at a loss how to configure firelens to allow multiline logs on Fargate.

right now it has:
```
          FirelensConfiguration:
            Type: fluentbit
            Options:
              enable-ecs-log-metadata: "true"
```

And the Work-Container:
```
          LogConfiguration:
            LogDriver: awsfirelens
            Options:
                Name: forward
                Host: fluentd.domain.tld
                Port: "24225"
```

So... Where to go from here? I'd like to avoid having to build my own image with custom config as would add maintenance costs.
