### ISSUE TITLE
Fluentbit S3 output causes prometheus metrics endpoint to be briefly unavailable. 

### ISSUE THREAD

**Issue by bharatnc** [aws/aws-for-fluent-bit#254]
### Describe the question/issue

Prometheus metrics endpoint /api/v1/metrics/prometheus is not available immediately with S3 Output and takes a long time for the interface to be available.

### Configuration

**Note:**  For credentials, `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` variables are used. These are exported and present in systemd environment when running fluentbit.

```
[SERVICE]
    flush        10
    daemon       Off
    log_level    info
    parsers_file /etc/flb/parsers.conf
    plugins_file /etc/flb/plugins.conf
    http_server  On
    http_listen  0.0.0.0
    http_port    3281
    storage.metrics On
    storage.path /fluentbit-buffer
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit  8M
    storage.max_chunks_up  128

[INPUT]
    Name  tail
    Alias  test_tail
    Path  /var/log/test.log
    Read_from_Head  Off
    Path_Key  filename
    Tag  syslog
    Key  event
    exit_on_eof  false
    Rotate_Wait  5
    Refresh_Interval  60
    Skip_Long_Lines  Off
    DB.sync  normal
    DB.locking  false
    Buffer_Chunk_Size  32k
    Buffer_Max_Size  8M
    Multiline  Off
    Multiline_Flush  4
    Parser_Firstline  8192
    Docker_Mode  Off
    Docker_Mode_Flush  4

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}

[OUTPUT]
    Name  s3
    Match  syslog
    endpoint  https://storage.googleapis.com
    bucket. fluentbit-test
    use_put_object true
    content_type  application/gzip
    compression gzip
    store_dir  /fluentbit/s3
    upload_timeout 1m
    region  us-west2
    total_file_size  1M
    s3_key_format  /99com25-test-k8s-s3/$UUID.gz
    s3_key_format_tag_delimiters .-
```

### Fluent Bit Log Output 
NA

### Fluent Bit Version Info

* Version used: 1.8.3 on bare metal using systemd unit (Debian stretch).

### Steps to reproduce issue

curl the metrics endpoint:
```
curl  http://localhost:3281/api/v1/metrics/prometheus
curl: (7) Failed to connect to localhost port 3281: Connection refused
```
**Expected behavior**

I should be able to curl the endpoint without seeing connection refused error instantaneously. Curl starts working only after a long time. This varies b/w my tests from attempt to attempt - generally 5-10 minutes and also happens to coincide with the first successful upload after buffering 1M of data (according to the settings I use above).

### Related Issues

https://github.com/fluent/fluent-bit/issues/4165

**Comment by hossain-rayhan** [comment]
Hi @bharatnc, does this happen only with S3 output plugin? Did you test with other output plugin like `stdout`?

Also, did you check the normal metrics endpoint instead of prometheus endpoint? Do you see any difference?

**Comment by matthewfala** [comment]
@bharatnc,
Could you let me know if running `kill -9 $(pgrep fluent-bit)` before spinning up a new fluent-bit process resolves your problem [2]?

**Comment by fvasco** [comment]
Hi @matthewfala,
we suspect to hit the same issue.
In our case, fluent-bit is a process in a container, so the port should be always available.

```yaml
spec:
  template:
    spec:
      containers:
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.11.0
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - find /var/log/flb-storage -cmin -30 | head -n 1 | grep . && curl -s
              http://localhost:2020/api/v1/metrics | grep '"errors":0'
          failureThreshold: 2
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: fluent-bit
        ports:
        - containerPort: 2020
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - find /var/log/flb-storage -cmin -30 | head -n 1 | grep . && curl -s
              http://localhost:2020/api/v1/metrics | grep '"errors":0'
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 80Mi
          requests:
            memory: 80Mi
        securityContext:
          capabilities:
            add:
            - SYSLOG
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/role: node
      priorityClassName: production
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /etc/machine-id
          type: ""
        name: machine-id
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - configMap:
          defaultMode: 420
          name: fluent-bit-config
        name: fluent-bit-config
```

The last working version is 2.11.0, any newer version fails to expose Prometheus metrics (so live check fails).

Our S3 configuration is simpler

~~~
    [OUTPUT]
        Name            s3
        Match           *
        region          us-east-1
        bucket          ${S3_BUCKET}
        s3_key_format   /fluent-bit-logs/%Y/%m/%d/%H/%M/%S/$TAG
        total_file_size 4M
        upload_timeout  1m
        compression     gzip
        use_put_object  true
~~~

Any suggestion?

**Comment by fvasco** [comment]
Version 2.21.2 still hangs at startup.


I executed the command: `kill -9 $(pgrep fluent-bit)`


The full log is:

~~~
Fluent Bit v1.8.9
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/03 13:09:20] [ info] [engine] started (pid=1)
[2021/12/03 13:09:20] [ info] [storage] version=1.1.5, initializing...
[2021/12/03 13:09:20] [ info] [storage] root path '/var/log/flb-storage/'
[2021/12/03 13:09:20] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/12/03 13:09:20] [ info] [storage] backlog input plugin: storage_backlog.4
[2021/12/03 13:09:20] [ info] [cmetrics] version=0.2.2
[2021/12/03 13:09:20] [ info] [input:systemd:systemd] seek_cursor=s=f9ed1dac9afc49069ac4fad3a1c066da;i=2be... OK
[2021/12/03 13:09:20] [ info] [input:storage_backlog:storage_backlog.4] queue memory limit: 95.4M
[2021/12/03 13:09:20] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2021/12/03 13:09:20] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2021/12/03 13:09:20] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2021/12/03 13:09:20] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2021/12/03 13:09:20] [ info] [fstore] created root path /tmp/fluent-bit/s3/xxx
[2021/12/03 13:09:20] [ info] [output:s3:s3.0] Using upload size 4000000 bytes
[2021/12/03 13:09:20] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2021/12/03 13:09:20] [ info] [sp] stream processor started
[2021/12/03 13:09:20] [error] [storage backlog] could not retrieve chunk tag
[2021/12/03 13:09:20] [error] [storage backlog] error distributing chunk references
[2021/12/03 13:09:20] [error] [engine] could not segregate backlog chunks
~~~

**Comment by matthewfala** [comment]
Thank you, @fvasco, for your details on the problem. I'll try to reproduce this again with your config next week.

**Comment by fvasco** [comment]
@matthewfala did you detect the memory leak?
Do you need more info?

**Comment by matthewfala** [comment]
Still haven't been able to reproduce yet. But the configuration you provided is helpful @fvasco. I'm working on some other fluent bit issues as well, but this is still something I'm trying to get done.

Also, what memory leak are you talking about? I thought that the issue is just that Fluent Bit prometheus endpoint hangs on startup?

**Comment by fvasco** [comment]
> what memory leak are you talking about?

My bad.
I am using a fluent-bit version with a memory leak.
The leak has been fixed in newer version but fluent-bit crashes at startup.
Thank you for your support, I will stay tuned.

**Comment by matthewfala** [comment]
Hmm, I still am unable to reproduce on Kubernetes...
It may be because I am using a simplified config to see if S3 output plugin is affecting the prometheus endpoint on startup. So far, seems that it isn't

I use 3 kubernetes resource config files which model your config but simplified down:
1. Fluent Bit config
```
apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Grace 30
        Log_Level debug
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_PORT     2020
    [INPUT]
        Name        forward
        Listen      0.0.0.0
        Port        24224
    [OUTPUT]
        Name s3 
        Match *
        bucket fluent-bit-bzs3
        total_file_size 1M
        upload_timeout 5m
        use_put_object On
        s3_key_format /$TAG[2]/$TAG[0]/%Y-%m-%d/%H-%M-%S-$UUID.gz
        auto_retry_requests true
    #     s3_key_format_tag_delimiters .-
        region us-west-2  
kind: ConfigMap
metadata:
  name: fluent-bit-config
```
2. Test App + FireLens
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-fbd
  labels:
    app: prometheus-fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-fb
  template:
    metadata:
      labels:
        app: prometheus-fb
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        ports:
        - containerPort: 2020
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 80Mi
          requests:
            memory: 80Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
        envFrom:
        - secretRef:
            name: aws-credentials
      - name: firelens-datajet
        image: public.ecr.aws/fala-fluentbit/firelens-datajet:0.1.1.r2-synchronizer
        env:
        - name: CLIENT_REQUEST_PORT
          value: "3210"
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
```
3. AWS Secrets
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
data:
  AWS_SECRET_ACCESS_KEY: <b64 secret>
  AWS_ACCESS_KEY_ID: <b64  key>
```

Upon startup, which is retried via: `kubectl scale deployment/pro-fbd --replicas=0` `kubectl scale deployment/pro-fbd --replicas=1`, I run this command to see if the prometheus endpoint is available:
```
kubectl get pods
kubectl exec -ti <my pod> --container=fluent-bit -- curl -i http://localhost:2020/api/v1/metrics/prometheus
```

The exec command results in the following:
```
HTTP/1.1 200 OK
Server: Monkey/1.7.0
Date: Wed, 22 Dec 2021 23:49:16 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; version=0.0.4

# HELP fluentbit_input_bytes_total Number of input bytes.
# TYPE fluentbit_input_bytes_total counter
fluentbit_input_bytes_total{name="forward.0"} 0 1640216957278
# HELP fluentbit_input_records_total Number of input records.
# TYPE fluentbit_input_records_total counter
fluentbit_input_records_total{name="forward.0"} 0 1640216957278
# HELP fluentbit_output_dropped_records_total Number of dropped records.
# TYPE fluentbit_output_dropped_records_total counter
fluentbit_output_dropped_records_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_errors_total Number of output errors.
# TYPE fluentbit_output_errors_total counter
fluentbit_output_errors_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_proc_bytes_total Number of processed output bytes.
# TYPE fluentbit_output_proc_bytes_total counter
fluentbit_output_proc_bytes_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_proc_records_total Number of processed output records.
# TYPE fluentbit_output_proc_records_total counter
fluentbit_output_proc_records_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_retried_records_total Number of retried records.
# TYPE fluentbit_output_retried_records_total counter
fluentbit_output_retried_records_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_retries_failed_total Number of abandoned batches because the maximum number of re-tries was reached.
# TYPE fluentbit_output_retries_failed_total counter
fluentbit_output_retries_failed_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_output_retries_total Number of output retries.
# TYPE fluentbit_output_retries_total counter
fluentbit_output_retries_total{name="s3.0"} 0 1640216957278
# HELP fluentbit_uptime Number of seconds that Fluent Bit has been running.
# TYPE fluentbit_uptime counter
fluentbit_uptime 40
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1640216917
# HELP fluentbit_build_info Build version information.
# TYPE fluentbit_build_info gauge
fluentbit_build_info{version="1.8.9",edition="Community"} 1
```

The S3 endpoint is tested via the test app, and logs are successfully sent to S3. The Prometheus endpoint is available on startup.

Would it be possible for you to try run the `kubectl exec -ti <my pod> --container=fluent-bit -- curl -i http://localhost:2020/api/v1/metrics/prometheus` command instead of exposing the endpoint via a service/tunnel and poking the endpoint on the host, or using it as a readiness probe? That way we can see if Fluent Bit is the problem or some networking between K8 and host.
