### ISSUE TITLE
Non-English character got UNICODE-escaped when getting logs from EKS to Cloudwatch logs

### ISSUE THREAD

**Issue by ensean** [aws/aws-for-fluent-bit#825]
### Describe the question/issue
Non-English characters in EKS log got UNICODE-escaped in Cloudwatch logs.

* Input logs
```
abc, today is a good day
好雨知时节
```
* Cloudwatch logs view
![image](https://github.com/aws/aws-for-fluent-bit/assets/12255172/31086cb7-526d-442e-8b92-fddab73c2e42)

This issue may related to https://github.com/fluent/fluent-bit/issues/8521, which can resolved via building fluent-bit on graviton with flag `-DCMAKE_C_FLAGS="-fsigned-char"`

### Configuration

part of EKS daemon set yaml
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: amazon-cloudwatch
  labels:
    k8s-app: fluent-bit
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        imagePullPolicy: Always
...
```
