### ISSUE TITLE
EFS Persistent Volume Errors

### ISSUE THREAD

**Issue by DanRidgway** [aws/aws-for-fluent-bit#841]
### Describe the question/issue
I have deployments running in EKS that is writing log files to AWS EFS Persistent Storage. Then I want fluent-bit to stream from the log to CloudWatch. The container crashes on start with the error.

NodeExpandVolume.NodeExpandVolume failed for volume "stream-fluentlog" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/efs.csi.aws.com to not support node expansion

### Configuration
Copy the example from 
https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit.yaml

Create a StorageClass, PersistentVolume, PersistentVolumeClaim that uses the efs.csi.aws.com driver.

Add this volume to the container spec.

### Fluent Bit Version Info
aws-for-fluent-bit:stable

###  Cluster Details
EKS
EC2
Fluent Bit Daemon

### Steps to reproduce issue
Do the configuration above and add the following to the DaemonSet
```
         volumeMounts:
            - mountPath: /mnt/Stream
              name: persistent-storage
         volumes:
           - name: persistent-storage
            persistentVolumeClaim:
               claimName: stream-fluentlog
```
